{% set name = "taxcalc" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PSLmodels/Tax-Calculator/archive/{{ version }}.tar.gz
  sha256: 61f5114e2bb10a5ebf4f3949f6efd9eb78836de1b6c8d7673d945a559a8b67cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tc = taxcalc.cli.tc:cli_tc_main

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy >=1.14
    - pandas >=1.2.0
    - bokeh >=1.4.0
    - requests
    - numba
    - paramtools >=0.18.0
    - aiohttp

test:
  imports:
    - taxcalc
  commands:
    - tc --help
    - tc --test

about:
  home: https://github.com/PSLmodels/Tax-Calculator
  license: CC0-1.0
  license_family: PUBLIC-DOMAIN
  license_file: docs/about/license.md
  summary: open-source microsimulation model for static analysis of USA federal income and payroll taxes.
  description: Tax-Calculator is an open-source microsimulation model for static analysis of USA federal income and payroll taxes.
  doc_url: http://taxcalc.pslmodels.org
  dev_url: https://github.com/PSLmodels/Tax-Calculator

extra:
  recipe-maintainers:
    - MattHJensen
